// Generated by CoffeeScript 1.6.3
$(function() {
  var addNode, force, g, height, links, nodes, tick, width;
  width = 960;
  height = 500;
  g = d3.select("body").append("svg").attr("width", width).attr("height", height);
  nodes = [];
  links = [];
  tick = function() {
    return g.selectAll("circle").attr("transform", function(d) {
      return "translate(" + d.x + ", " + d.y + ")";
    });
  };
  force = d3.layout.force().nodes(nodes).links(links).size([width, height]).on("tick", tick);
  addNode = function() {
    var node;
    node = {
      id: nodes.length + 1
    };
    nodes.push(node);
    g.selectAll("circle").data(nodes).enter().append("circle").attr("r", 10).call(force.drag);
    return force.start();
  };
  $("#add-node").click(addNode);
  $("#rename-node").click(renameNode);
  return $("#delete-node").click(deleteNode);
});
